version: "3.9"

services:
  portal:
    build: .
    environment:
      PYTHONHASHSEED: 0
    ports:
      - 8000:8000
    volumes:
      - "./instance:/project/instance"
  redis:
    image: "redis:latest"
    ports:
      - 6380:6379
